sonar.sources=screens
sonar.tests=__tests__
sonar.exclusions=node_modules/**,coverage/**,assets/**,**/*.config.js,babel.config.js,jest.setup.js,index.ts
sonar.cpd.exclusions=screens/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info


