sonar.projectKey=L02-hello-mobile_assignment-mobile
sonar.organization=l02-hello-mobile
sonar.sources=screens
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,assets/**,*.config.js,babel.config.js
sonar.test.exclusions=node_modules/**
sonar.coverage.exclusions=**/__tests__/**