sonar.projectKey=L02-hello-mobile_assignment-mobile
sonar.organization=l02-hello-mobile

# Khai báo nguồn mã nguồn và test [cite: 389, 395]
sonar.sources=screens
sonar.tests=__tests__

# Chỉ đường dẫn file kết quả coverage [cite: 396]
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Loại trừ các file rác để không bị lỗi ảo (442 bugs) [cite: 15, 229]
sonar.exclusions=node_modules/**, coverage/**, __tests__/**, **/*.test.tsx, **/*.test.ts, babel.config.js, jest.config.js, jest.setup.js, app.json, package.json, package-lock.json